### ISSUE TITLE
Latest T50 not performing TCP flood

### ISSUE THREAD

**Issue by dcbeckett** [fredericopissarra/t50#12]
If I carry out the following command on the latest commit it responds with an error.

Command - sudo ./t50 10.10.10.101 -S --flood
Error - T50: One or more options are not available to chosen protocol.

I can't seem to get any of the TCP traffic commands to work with the current commit, however when I download the release- v5-5.rc1 the same commands work fine. Must be a bug in some of the latest changes?

**Comment by dcbeckett** [comment]
Thought I'd do some investigatory work, The code up to the 13 May is working fine, however the commit on 14 May "Added cheking for opitions invalid for a choosen protocol. Need refinements yet" seems to be causing this issue.

I'm happy just using the 5.5-rc1 release version, but may be best taking this out of the master branch until it's in a working condition?

**Comment by samueloph** [comment]
Hi @fredericopissarra, is this fixed already? There were a lot of commits going on since this was reported and some of the commit messages makes it very hard to track changes.

**Comment by fredericopissarra** [comment]
Yes it is fixed...

**Comment by Marcosfou** [comment]
Hello
I just cloned the last release (5.6.3 at this time) (also tried the tarball from Sourceforge) and  this issue is not fixed. 

Should be good a new release with the fix.

**Comment by fredericopissarra** [comment]
What are your test conditions?
Any error messages?

[]s
Fred

**Comment by Marcosfou** [comment]
Hello Frederico
Thanks for the quick response! 
I'm using Debian Testing. It compiled cleanly but i get the same error than dcbeckett.

# t50 --threshold 500 192.168.0.100
t50: One or more options are not available to chosen protocol.

The same goes when i use other options like --flood.

Regards.

**Comment by fredericopissarra** [comment]
Try to give the IP first or use --:

# t50 --threshold 500 -- 192.168.0.100

or

# t50 192.168.0.100 --threshold 500

In fact, this is a bug on the new command line parser detected long ago. 
I'll fix it, eventually.

[]s
Fred

**Comment by fredericopissarra** [comment]
Marcos, this bug is fixed now.
I've uploaded the fixed package to sourceforge and it's available in 
Github as well...

Thanks a lot!

**Comment by samueloph** [comment]
@Marcosfou @dcbeckett Just be carefull because @fredericopissarra substitute the 5.6.3 release with one containing this fix, which means that right now there are two T50 releases for 5.6.3, one fixed at sf and one problematic here on github.

I talked to frederico on facebook and explained the problems with changing releases this way (without making a new one) and he said he prefer this way, so i wanted to warn you and whoever want to install or package T50 that releases of the same version may differ from sf and github.

**Comment by fredericopissarra** [comment]
@samueloph @Marcosfou @dcbeckett THERE IS ONLY ONE release 5.6.3 on BOTH github and sf.
Both with the latetest fixes...

**Comment by fredericopissarra** [comment]
And @Marcosfou... thanka a lot to get my attention to this nasty bug... ;)

**Comment by samueloph** [comment]
@fredericopissarra I see that you're not familiar with git[1], i'm gonna try to give an explanation, the commits applied on the master branch do not count as commits applied on the release, you can not just try to overwrite a release (which sf allowed you to do)[2], you have to make a new one even for small fixes, that's one use for semantic versioning (i believe is what T50 uses).

What happened is that you can download T50 5.6.3 at https://github.com/fredericopissarra/t50/releases/tag/v5.6.3 without the fix (the original release) and one T50 5.6.3 at https://sourceforge.net/projects/t50/files/t50-5.6/t50-5.6.3.tar.gz/download fixed (the release you did overwrite).

I truly recommend reversing that sf release, putting the original one back on, and creating a new release 5.6.4 with this fix.

I'm sorry if i sound rude, but please have a look at my considerations.

[1] The commit messages all over the log are confusing, but that's not really the case here.
[2] Considering what we talked on facebook, i believe you still not convinced on why overwriting a release is awful, but i truly believe talking with someone experienced on project management would help, again, please don't get me wrong.

**Comment by fredericopissarra** [comment]
Ahhhh.... "What happened is that you can download T50 5.6.3 at https://github.com/fredericopissarra/t50/releases/tag/v5.6.3 without the fix"... that's right!

Release 5.6.4 posted.

Thanks.

**Comment by Marcosfou** [comment]
Hello everyone!

I did not mention that, but i am trying to package it for Debian (i am a newbie member of pkg-security tools team) and i believe that samueloph is right. I would be a pretty mess with packaging if we have two diferent versions whit the same numbering.

Now it should be right. If there is no more issues, i will upload to Debian git in no time!

Cheers.

Marcos

**Comment by samueloph** [comment]
Hi @Marcosfou I'm from the forensics team, I mentioned on some email at debian-devel [i believe] announcing the security team that i was working on the T50 package.

Since it clearly looks like you're ahead of me (i would upload it only during the next week and did not do much work yet on the package), please feel free to go ahead, i will be asking for joining the team next week too, so we'll probably be working together :)

I have some worries about T50 regarding problems like this, i'll be in touch next week to talk about them.

**Comment by Marcosfou** [comment]
Cool! @samueloph drop me a mail at mfouces NOSPAM yahoo.es and we work together on it.
